RizzPick/RizzPick-backend

build.gradle, src/main/java/com/willyoubackend/domain/user/config/WebSecurityConfig.java, src/main/java/com/willyoubackend/domain/user/controller/UserController.java, src/main/java/com/willyoubackend/domain/user/dto/LoginRequestDto.java, src/main/java/com/willyoubackend/domain/user/dto/SignupRequestDto.java, src/main/java/com/willyoubackend/domain/user/dto/SignupResponseDto.java, src/main/java/com/willyoubackend/domain/user/dto/UserInfoDto.java, src/main/java/com/willyoubackend/domain/user/entity/UserEntity.java, src/main/java/com/willyoubackend/domain/user/entity/UserRoleEnum.java, src/main/java/com/willyoubackend/domain/user/jwt/JwtUtil.java, src/main/java/com/willyoubackend/domain/user/repository/UserRepository.java, src/main/java/com/willyoubackend/domain/user/security/JwtAuthenticationFilter.java, src/main/java/com/willyoubackend/domain/user/security/JwtAuthorizationFilter.java, src/main/java/com/willyoubackend/domain/user/security/UserDetailsImpl.java, src/main/java/com/willyoubackend/domain/user/security/UserDetailsServiceImpl.java, src/main/java/com/willyoubackend/domain/user/service/UserService.java
로그인 및 회원가입 API 개발
Resolves: #1
Ref: None
=> [#1] Feat: "로그인 및 회원가입 구현"

src/main/java/com/willyoubackend/domain/user/config/RestTemplateConfig.java, src/main/java/com/willyoubackend/domain/user/controller/UserController.java, src/main/java/com/willyoubackend/domain/user/dto/KakaoUserInfoDto.java, src/main/java/com/willyoubackend/domain/user/dto/SignupResponseDto.java, src/main/java/com/willyoubackend/domain/user/entity/UserEntity.java, src/main/java/com/willyoubackend/domain/user/jwt/JwtUtil.java, src/main/java/com/willyoubackend/domain/user/repository/UserRepository.java, src/main/java/com/willyoubackend/domain/user/security/JwtAuthenticationFilter.java, src/main/java/com/willyoubackend/domain/user/security/JwtAuthorizationFilter.java, src/main/java/com/willyoubackend/domain/user/security/UserDetailsImpl.java, src/main/java/com/willyoubackend/domain/user/security/UserDetailsServiceImpl.java, src/main/java/com/willyoubackend/domain/user/service/KakaoService.java, src/main/java/com/willyoubackend/domain/user/service/UserService.java
카카오 소셜로그인 API 개발
Resolves: #4
Ref: None
Related to: #1 카카오 소셜 로그인 관련 entity 및 repository에 코드추가
=> [#4] Feat/#4 카카오 소셜로그인 구현

.gitignore, src/main/resources/application.properties
RDS 연결 및 application.properties 변경
Resolves: #3
Ref: None
=> [#3]Feat: "RDS Config"

build.gradle, src/main/java/com/willyoubackend/global/config/S3Config.java, src/main/java/com/willyoubackend/global/util/S3Uploader.java
S3 config done, S3Config.java and S3Uploader.java implemented
Resolves: #11
Ref: None
=> [#11]Feat: "S3 config"

src/main/java/com/willyoubackend/domain/user/entity/UserEntity.java, src/main/java/com/willyoubackend/domain/user_profile/controller/UserProfileController.java, src/main/java/com/willyoubackend/domain/user_profile/dto/ProfileImageRequestDto.java, src/main/java/com/willyoubackend/domain/user_profile/dto/StatusResponseDto.java, src/main/java/com/willyoubackend/domain/user_profile/dto/UserProfileRequestDto.java, src/main/java/com/willyoubackend/domain/user_profile/entity/GenderEnum.java, src/main/java/com/willyoubackend/domain/user_profile/entity/LocationEnum.java, src/main/java/com/willyoubackend/domain/user_profile/entity/MbtiEnum.java, src/main/java/com/willyoubackend/domain/user_profile/entity/ProfileImageEntity.java, src/main/java/com/willyoubackend/domain/user_profile/entity/ReligionEnum.java, src/main/java/com/willyoubackend/domain/user_profile/entity/UserProfileEntity.java, src/main/java/com/willyoubackend/domain/user_profile/repository/UserProfileRepository.java, src/main/java/com/willyoubackend/domain/user_profile/service/UserProfileService.java, src/main/java/com/willyoubackend/global/exception/ErrorCode.java
유저 프로필 업데이트
Resolves: #7
Ref: None
Related to: #1
=> [#7]Feat: "user Profile Update"

src/main/java/com/willyoubackend/domain/user/config/WebSecurityConfig.java, src/main/java/com/willyoubackend/global/config/CorsConfig.java
WebSecurityConfig.java and CorsConfig.java modified and created
Be aware of conflicts related to WebSecurityConfig.java
Resolves: #15
Ref: None
Related to: #1
=> [#15]Feat: "CORS config"

src/main/java/com/willyoubackend/domain/user_profile/controller/UserProfileController.java, src/main/java/com/willyoubackend/domain/user_profile/entity/UserProfileEntity.java, src/main/java/com/willyoubackend/domain/user_profile/service/ProfileImageService.java, src/main/java/com/willyoubackend/domain/user_profile/service/UserProfileService.java
유저 프로필 설정 수정
Resolves: #20
Ref: None
Related to: #7
=> [#20]Fix: "User Profile Update"

build.gradle, src/main/java/com/willyoubackend/domain/user/controller/UserController.java, src/main/java/com/willyoubackend/domain/user/dto/EmailRequest.java, src/main/java/com/willyoubackend/domain/user/dto/VerifiRequest.java, src/main/java/com/willyoubackend/domain/user/service/UserService.java, src/main/java/com/willyoubackend/global/config/RedisConfig.java, src/main/java/com/willyoubackend/global/exception/ErrorCode.java, src/main/java/com/willyoubackend/global/util/RedisUtil.java
Redis 이용, 이메일 인증번호 요청, 인증기능 구현
Resolves: #10
Ref: None
Related to: #1
=> [#10]Feat: "Email send & verify"

build.gradle, src/main/java/com/willyoubackend/domain/user/config/WebSecurityConfig.java, src/main/java/com/willyoubackend/domain/user/dto/KakaoUserInfoDto.java, src/main/java/com/willyoubackend/domain/user/entity/RefreshToken.java, src/main/java/com/willyoubackend/domain/user/entity/UserEntity.java, src/main/java/com/willyoubackend/domain/user/jwt/JwtUtil.java, src/main/java/com/willyoubackend/domain/user/repository/RefreshTokenRepository.java, src/main/java/com/willyoubackend/domain/user/security/JwtAuthenticationFilter.java, src/main/java/com/willyoubackend/domain/user/security/JwtAuthorizationFilter.java, src/main/java/com/willyoubackend/domain/user/service/KakaoService.java
Refresh Token추가
Refresh Token AccessToken 중복 값으로 입력되는 문제 발생
Resolves: #23
Ref: #1 #4
Related to: #1 #4
=> [#23] Feat: "Add Refresh Token"

src/main/java/com/willyoubackend/domain/user/jwt/JwtUtil.java, src/main/java/com/willyoubackend/domain/user/security/JwtAuthenticationFilter.java, src/main/java/com/willyoubackend/domain/user/service/UserService.java
Refresh Token AccessToken 중복 값으로 입력되는 문제 해결
Resolves: #23
Ref: #1 #4
=> [#23] Fix: "Refresh Token"

src/main/java/com/willyoubackend/domain/user/repository/UserRepository.java, src/main/java/com/willyoubackend/domain/user_profile/controller/UserProfileController.java, src/main/java/com/willyoubackend/domain/user_profile/dto/StatusResponseDto.java, src/main/java/com/willyoubackend/domain/user_profile/dto/UserProfileResponseDto.java, src/main/java/com/willyoubackend/domain/user_profile/service/UserProfileService.java
프로필 전체/상세 조회
Resolves: #22
Ref: None
=> [#22]Feat: "Get User Profile/Profiles"

src/main/java/com/willyoubackend/WillYouBackendApplication.java, src/main/java/com/willyoubackend/domain/dating/controller/DatingController.java, src/main/java/com/willyoubackend/domain/dating/dto/DatingRequestDto.java, src/main/java/com/willyoubackend/domain/dating/dto/DatingResponseDto.java, src/main/java/com/willyoubackend/domain/dating/entity/Dating.java, src/main/java/com/willyoubackend/domain/dating/entity/DatingThemeEnum.java, src/main/java/com/willyoubackend/domain/dating/repository/DatingRepository.java, src/main/java/com/willyoubackend/domain/dating/service/DatingService.java, src/main/java/com/willyoubackend/global/entity/Timestamped.java
Dating entity, controller, service, dto, and repository implemented.
Resolves: #17
Ref: None
=> [#17]Feat: "Dating Basic Implementation"

src/main/java/com/willyoubackend/domain/user_profile/controller/UserProfileController.java, src/main/java/com/willyoubackend/domain/user_profile/service/UserProfileService.java
프로필 전체, 상세 조회 수정(ApiResponse)
Resolves: #31
Ref: None
Related to: #22
=> [#31]Fix: "Get User Profile/Profiles"

src/main/java/com/willyoubackend/domain/dating/controller/ActivityController.java, src/main/java/com/willyoubackend/domain/dating/dto/ActivityRequestDto.java, src/main/java/com/willyoubackend/domain/dating/dto/ActivityResponseDto.java, src/main/java/com/willyoubackend/domain/dating/entity/Activity.java, src/main/java/com/willyoubackend/domain/dating/repository/ActivityRepository.java, src/main/java/com/willyoubackend/domain/dating/service/ActivityService.java
Activity entity, controller, service, dto, and repository implemented.
Resolves: #30
Ref: None
=> [#30]Feat: "Activity Basic Implementation"

src/main/java/com/willyoubackend/domain/dating/controller/ActivityController.java, src/main/java/com/willyoubackend/domain/dating/controller/DatingController.java, src/main/java/com/willyoubackend/domain/dating/dto/DatingDetailResponseDto.java, src/main/java/com/willyoubackend/domain/dating/entity/ActivitiesDating.java, src/main/java/com/willyoubackend/domain/dating/repository/ActivitiesDatingRepository.java, src/main/java/com/willyoubackend/domain/dating/service/ActivityService.java, src/main/java/com/willyoubackend/domain/dating/service/DatingService.java
ActivitiesDating entity, and repository implemented. Activity & Dating modified
Resolves: #34
Ref: None
Related to: #17, #30
=> [#34]Feat: "Dating and Activities Connected"

build.gradle, src/main/java/com/willyoubackend/domain/user/config/WebSecurityConfig.java, src/main/java/com/willyoubackend/domain/user/controller/UserController.java
Swagger configured - build.gradle, WebSecurityConfig.java and UserController.java modified
Resolves: #36
Ref: None
Related to: Every issue
=> [#36]Feat: "Dating and Activities Connected"

src/main/java/com/willyoubackend/global/config/OpenApiConfig.java
Swagger configured to be deployed
Resolves: #39
Ref: None
Related to: #36
=> [#39]Feat: "OpenApi for deploy"

src/main/java/com/willyoubackend/global/config/OpenApiConfig.java
Swagger Auth Setting
Resolves: #41
Ref: None
Related to: #39
=> [#41]Add: "OpenApi Auth Done"

src/main/java/com/willyoubackend/domain/user_profile/controller/UserProfileController.java, src/main/java/com/willyoubackend/domain/user_profile/dto/SetMainDatingRequestDto.java, src/main/java/com/willyoubackend/domain/user_profile/dto/UserProfileResponseDto.java, src/main/java/com/willyoubackend/domain/user_profile/entity/UserProfileEntity.java, src/main/java/com/willyoubackend/domain/user_profile/service/UserProfileService.java
대표 데이트 설정 및 삭제(프로필)
Resolves: #38
Ref: None
=> [#38]Feat: "MainDating(UserProfile)"

src/main/java/com/willyoubackend/domain/user_profile/controller/ProfileImageController.java, src/main/java/com/willyoubackend/domain/user_profile/controller/UserProfileController.java
UserProfileController, ProfileImageController Swagger
Resolves: #46
Ref: None
=> [#46]Fix: "Swagger"

src/main/java/com/willyoubackend/domain/user_profile/controller/ProfileImageController.java, src/main/java/com/willyoubackend/domain/user_profile/service/ProfileImageService.java
프로필 다중 이미지 업로드
Resolves: #48
Ref: None
Related to: #14
=> [#48]Fix: "Multiple Profile Images Upload"

src/main/java/com/willyoubackend/domain/user_like_match/controller/UserLikeNopeController.java, src/main/java/com/willyoubackend/domain/user_like_match/controller/UserLikeNopeStatusController.java, src/main/java/com/willyoubackend/domain/user_like_match/controller/UserMatchStatusController.java, src/main/java/com/willyoubackend/domain/user_like_match/dto/LikeNopeResponseDto.java, src/main/java/com/willyoubackend/domain/user_like_match/dto/LikeStatusResponseDto.java, src/main/java/com/willyoubackend/domain/user_like_match/dto/MatchResponseDto.java, src/main/java/com/willyoubackend/domain/user_like_match/entity/UserLikeStatus.java, src/main/java/com/willyoubackend/domain/user_like_match/entity/UserMatchStatus.java, src/main/java/com/willyoubackend/domain/user_like_match/entity/UserNopeStatus.java, src/main/java/com/willyoubackend/domain/user_like_match/repository/UserLikeStatusRepository.java, src/main/java/com/willyoubackend/domain/user_like_match/repository/UserMatchStatusRepository.java, src/main/java/com/willyoubackend/domain/user_like_match/repository/UserNopeStatusRepository.java, src/main/java/com/willyoubackend/domain/user_like_match/service/UserLikeService.java, src/main/java/com/willyoubackend/domain/user_like_match/service/UserLikeStatusService.java, src/main/java/com/willyoubackend/domain/user_like_match/service/UserMatchStatusService.java, src/main/java/com/willyoubackend/domain/user_like_match/service/UserNopeService.java, src/main/java/com/willyoubackend/global/exception/ErrorCode.java
User Like and Match done
Resolves: #44
Ref: None
=> [#44]Add: "Like & Match"

src/main/java/com/willyoubackend/domain/dating/controller/ActivityController.java, src/main/java/com/willyoubackend/domain/dating/controller/DatingController.java, src/main/java/com/willyoubackend/domain/user_like_match/controller/UserLikeNopeController.java, src/main/java/com/willyoubackend/domain/user_like_match/controller/UserLikeNopeStatusController.java, src/main/java/com/willyoubackend/domain/user_like_match/controller/UserMatchStatusController.java
Swagger docs added for Like, Match, Dating and Activity Controller
Resolves: #52
Ref: None
=> [#52]Add: "Swagger added Like Match Dating and Activity"

src/main/java/com/willyoubackend/domain/user_profile/controller/ProfileImageController.java, src/main/java/com/willyoubackend/domain/user_profile/dto/ImageActionEnum.java, src/main/java/com/willyoubackend/domain/user_profile/dto/ProfileImageRequestDto.java, src/main/java/com/willyoubackend/domain/user_profile/entity/ProfileImageEntity.java, src/main/java/com/willyoubackend/domain/user_profile/service/ProfileImageService.java, src/main/java/com/willyoubackend/global/util/S3Uploader.java
프로필 이미지 수정 삭제
Resolves: #50
Ref: None
Related to: #48
=> [#50]Feat: "Profile Image Modify / Delete"

build.gradle, src/main/java/com/willyoubackend/domain/user/config/WebSecurityConfig.java, src/main/java/com/willyoubackend/domain/user/service/KakaoService.java
Cors -> corsMappingAdded
Kakao -> Service modified(username)
Resolves: #60
Ref: None
Related to: #1 #4
=> [#60]Fix: "CORS, WebSecurityConfig and Kakao Bug fix"

src/main/java/com/willyoubackend/domain/user/service/UserService.java, src/main/resources/application.properties
유저 프로필 엔터티 생성(회원가입)
Resolves: #59
Ref: None
=> [#59]Feat: "Create UserProfileEntity"

src/main/java/com/willyoubackend/domain/user_profile/entity/UserProfileEntity.java, src/main/java/com/willyoubackend/domain/user_profile/repository/ProfileImageRepository.java, src/main/java/com/willyoubackend/domain/user_profile/service/ProfileImageService.java, src/main/java/com/willyoubackend/domain/user_profile/service/UserProfileService.java, src/main/java/com/willyoubackend/global/exception/ErrorCode.java
유저 활성화 상태 변경(닉네임, 성별 입력시 true)
Resolves: #64
Ref: None
=> [#64]Feat: "User Active Status(false->true)"

src/main/java/com/willyoubackend/domain/user/controller/UserController.java, src/main/java/com/willyoubackend/domain/user/dto/KakaoUserInfoDto.java, src/main/java/com/willyoubackend/domain/user/dto/LoginResponseDto.java, src/main/java/com/willyoubackend/domain/user/service/KakaoService.java, src/main/java/com/willyoubackend/domain/user/service/UserService.java, src/main/java/com/willyoubackend/domain/user_profile/repository/UserProfileRepository.java
User Active status added for Social Login and Normal Login
Resolves: #62
Ref: None
Related to: #1 #4
=> [#62]Add: "User Active Status added"

src/main/java/com/willyoubackend/domain/user_profile/dto/ProfileImageRequestDto.java, src/main/java/com/willyoubackend/domain/user_profile/service/ProfileImageService.java, src/main/java/com/willyoubackend/global/exception/ErrorCode.java
프로필 이미지 개수 제한(1~6)
Resolves: #70
Ref: None
=> [#70]Fix: "프로필 이미지 개수 제한"

src/main/java/com/willyoubackend/domain/user_profile/controller/UserProfileController.java, src/main/java/com/willyoubackend/domain/user_profile/service/UserProfileService.java
회원 프로필 업데이트 리턴 타입 변경
Resolves: #74
Ref: None
=> [#74]Fix: "Return fix : updateProfile"

src/main/java/com/willyoubackend/domain/user_profile/dto/UserProfileResponseDto.java, src/main/java/com/willyoubackend/domain/user_profile/entity/LocationEnum.java, src/main/java/com/willyoubackend/domain/user_profile/entity/MbtiEnum.java, src/main/java/com/willyoubackend/domain/user_profile/entity/ReligionEnum.java
Enum, User Profile bug fix
Resolves: #72
Ref: None
=> [#72]Add: "Enum modified"

src/main/java/com/willyoubackend/domain/user_profile/controller/UserProfileController.java, src/main/java/com/willyoubackend/domain/user_profile/dto/ImageResponseDto.java, src/main/java/com/willyoubackend/domain/user_profile/dto/UserProfileResponseDto.java, src/main/java/com/willyoubackend/domain/user_profile/service/UserProfileService.java
마이 프로필 조회
Resolves: #79
Ref: None
=> [#79]Feat: "GetMyProfile"

src/main/java/com/willyoubackend/domain/user_profile/controller/ProfileImageController.java, src/main/java/com/willyoubackend/domain/user_profile/service/ProfileImageService.java
프로필 이미지 설정 리턴 값 변경
Resolves: #81
Ref: None
=> [#81]Fix: "updateProfileImage(return)"

src/main/java/com/willyoubackend/domain/dating/service/ActivityService.java, src/main/java/com/willyoubackend/domain/dating/service/DatingService.java, src/main/java/com/willyoubackend/domain/user_like_match/service/UserLikeService.java, src/main/java/com/willyoubackend/domain/user_like_match/service/UserMatchStatusService.java, src/main/java/com/willyoubackend/domain/user_like_match/service/UserNopeService.java
Detail conditions added
Resolves: #71
Ref: None
=> [#71]Add: "Activity Dating modified"

src/main/java/com/willyoubackend/domain/user/jwt/JwtUtil.java, src/main/java/com/willyoubackend/domain/user/security/JwtAuthenticationFilter.java
Returning ID and Active status of user
Resolves: #85
Ref: None
=> [#85]fix: "Login Response Dto & Token time modified"

build.gradle
QueryDSL 설정
Resolves: #84
Ref: None
=> [#84]Feat: "Set QueryDSL"

src/main/java/com/willyoubackend/domain/user/service/KakaoService.java
Kakao Fixed
Resolves: #89
Ref: None
=> [#89]Add: "Kakao Login Fixed"

src/main/java/com/willyoubackend/domain/user/config/WebSecurityConfig.java, src/main/java/com/willyoubackend/domain/user/controller/UserController.java, src/main/java/com/willyoubackend/domain/user/dto/TokenResponseDto.java, src/main/java/com/willyoubackend/domain/user/jwt/JwtUtil.java
New AccessToken Api
Resolves: #92
Ref: None
=> [#92] Feat: "New AccessToken Api"

src/main/java/com/willyoubackend/domain/user/controller/UserController.java, src/main/java/com/willyoubackend/domain/user/dto/TokenRequestDto.java, src/main/java/com/willyoubackend/domain/user/entity/RefreshToken.java, src/main/java/com/willyoubackend/domain/user/jwt/JwtUtil.java, src/main/java/com/willyoubackend/domain/user/repository/RefreshTokenRepository.java, src/main/java/com/willyoubackend/domain/user/security/JwtAuthenticationFilter.java, src/main/java/com/willyoubackend/domain/user/security/JwtAuthorizationFilter.java, src/main/java/com/willyoubackend/domain/user/service/UserService.java, src/main/java/com/willyoubackend/global/exception/ErrorCode.java
Login Access Token
Resolves: #94
Ref: None
=> [#94]Add: "Login Access token modified"

src/main/java/com/willyoubackend/domain/user/jwt/JwtUtil.java
Websocket develop
Resolves: #96
Ref: None
=> [#96]Add: "Merged: Websocket Develop"

build.gradle, src/main/java/com/willyoubackend/domain/websocket/controller/ChatController.java, src/main/java/com/willyoubackend/domain/websocket/controller/ChatRoomController.java, src/main/java/com/willyoubackend/domain/websocket/dto/ChatMessage.java, src/main/java/com/willyoubackend/domain/websocket/repository/ChatMessageRepository.java, src/main/java/com/willyoubackend/domain/websocket/repository/MongoChatRoomRepository.java, src/main/java/com/willyoubackend/domain/websocket/service/ChatMessageService.java, src/main/resources/templates/chat/roomdetail.html
채팅메시지, 채팅방 MongoDB에 저장, 소프트 딜리트 간단 구현
Resolves: None
Ref: #42
Related to: #42
=> [#42] Add: "WebSocket MongoDB"

src/main/java/com/willyoubackend/domain/websocket/config/StompHandler.java, src/main/java/com/willyoubackend/domain/websocket/config/WebSockConfig.java, src/main/java/com/willyoubackend/domain/websocket/controller/ChatController.java, src/main/java/com/willyoubackend/domain/websocket/controller/ChatRoomController.java, src/main/java/com/willyoubackend/domain/websocket/dto/ChatMessage.java, src/main/java/com/willyoubackend/domain/websocket/dto/ChatRoom.java, src/main/java/com/willyoubackend/domain/websocket/repository/ChatMessageRepository.java, src/main/java/com/willyoubackend/domain/websocket/repository/ChatRoomRepository.java, src/main/java/com/willyoubackend/domain/websocket/repository/MongoChatRoomRepository.java, src/main/java/com/willyoubackend/domain/websocket/service/ChatMessageService.java, src/main/java/com/willyoubackend/domain/websocket/service/RedisSubscriber.java
mongoDB 연결 오류 수정
Resolves: None
Ref: #42
Related to: #42
=> [#42] Fix: "WebSocket MongoDB"

src/main/java/com/willyoubackend/domain/websocket/config/WebSockConfig.java
프론트 wss:// 엔드포인트 추가
Resolves: None
Ref: #42
Related to: #42
=> [#42] Fix: "WebSocket Endpoint"

src/main/java/com/willyoubackend/domain/user_like_match/controller/UserLikeNopeStatusController.java, src/main/java/com/willyoubackend/domain/user_like_match/dto/LikeAlertResponseDto.java, src/main/java/com/willyoubackend/domain/user_like_match/service/UserLikeStatusService.java
Like Alert Updated for main page
Resolves: #102
Ref: None
=> [#102]Feat: "Like Alert Updated"

src/main/java/com/willyoubackend/domain/user/repository/UserRepository.java, src/main/java/com/willyoubackend/domain/user/repository/UserRepositoryCustom.java, src/main/java/com/willyoubackend/domain/user/repository/UserRepositoryImpl.java, src/main/java/com/willyoubackend/domain/user_profile/repository/ProfileImageRepositoryCustom.java, src/main/java/com/willyoubackend/domain/user_profile/repository/ProfileImageRepositoryImpl.java, src/main/java/com/willyoubackend/domain/user_profile/repository/UserProfileRepositoryCustom.java, src/main/java/com/willyoubackend/domain/user_profile/repository/UserProfileRepositoryImpl.java, src/main/java/com/willyoubackend/global/config/QuerydslConfig.java
QueryDSL 적용
Resolves: #88
Ref: None
=> [#88]Feat: "QueryDSL"

src/main/java/com/willyoubackend/domain/user_profile/dto/UserProfileRequestDto.java, src/main/java/com/willyoubackend/domain/user_profile/dto/UserProfileResponseDto.java, src/main/java/com/willyoubackend/domain/user_profile/entity/UserProfileEntity.java
유저프로필 칼럼 추가(intro : 자기소개)
Resolves: #106
Ref: None
=> [#106]Fix: "UserProfile-add-Column(intro)"

src/main/java/com/willyoubackend/domain/user_like_match/repository/UserLikeStatusRepository.java, src/main/java/com/willyoubackend/domain/user_like_match/repository/UserNopeStatusRepository.java, src/main/java/com/willyoubackend/domain/user_profile/entity/UserRecommendations.java, src/main/java/com/willyoubackend/domain/user_profile/repository/UserRecommendationsRepository.java, src/main/java/com/willyoubackend/domain/user_profile/service/UserProfileService.java
USER recommendations applied
Resolves: #103
Ref: None
=> [#103]Feat: "User Recommendations RedisHash Applied"

src/main/java/com/willyoubackend/domain/websocket/service/ChatMessageService.java, src/main/java/com/willyoubackend/domain/websocket/service/ChatRoomService.java
@MessageMapping doesn't allow @AuthenticationPrincipal
Resolves: #112
Ref: None
=> [#112] Fix: "Realtime messages bug fixed"

src/main/java/com/willyoubackend/domain/user/repository/UserRepositoryImpl.java
쿼리 최적화
Resolves: #111
Ref: None
=> [#111]Fix: "Query Optimization"

src/main/java/com/willyoubackend/domain/user_like_match/service/UserLikeService.java, src/main/java/com/willyoubackend/domain/websocket/entity/ChatRoomDto.java, src/main/java/com/willyoubackend/domain/websocket/repository/ChatMessageRepository.java, src/main/java/com/willyoubackend/domain/websocket/service/ChatRoomService.java
내가 있는 채팅방 목록 조회 시 최근 메시지 내용 추가
Resolves: None
Ref: #108
=> [#108] Fix: "ChatRoom"

src/main/java/com/willyoubackend/domain/user_like_match/service/UserMatchStatusService.java, src/main/java/com/willyoubackend/domain/websocket/controller/ChatMessageController.java, src/main/java/com/willyoubackend/domain/websocket/controller/ChatRoomController.java, src/main/java/com/willyoubackend/domain/websocket/repository/ChatMessageRepository.java
ChatRoom 관련 API SWaager 추가,
매치 취소 시 해당 채팅방에 관련된 모든 SocketMessage가 삭제 처리 추가
Resolves: None
Ref: #108
=> [#108] Add: "ChatRoom"

src/main/java/com/willyoubackend/domain/user/service/UserService.java
이메일 요청 시 이메일 중복 확인 추가
Resolves: #10
Ref: None
=> [#10] Add: "Email send & verify"

src/main/java/com/willyoubackend/domain/dating/dto/ActivityRequestDto.java, src/main/java/com/willyoubackend/domain/dating/dto/ActivityResponseDto.java, src/main/java/com/willyoubackend/domain/dating/entity/Activity.java, src/main/java/com/willyoubackend/domain/dating/service/ActivityService.java, src/main/java/com/willyoubackend/domain/dating/service/DatingService.java, src/main/java/com/willyoubackend/domain/user/entity/RefreshToken.java
Title removed and minor fix for RefreshTokens and Dating
Resolves: #122
Ref: None
=> [#122] Fix: "Activity Update"

build.gradle, src/main/java/com/willyoubackend/global/config/RedisConfig.java
mySQL 로 chatRoom 옮기기 전 EC2 에 Redis server config
Resolves: #126
Ref: None
=> [#126] Fix: "EC2 Redis Server"

src/main/java/com/willyoubackend/domain/websocket/service/ChatRoomService.java, src/main/java/com/willyoubackend/global/exception/ErrorCode.java
java.lang.IllegalArgumentException: The given id must not be null라는 예외처리
Resolves: #126
Ref: None
=> [#126] Fix: "Exception"

src/main/java/com/willyoubackend/domain/user_profile/controller/UserProfileController.java, src/main/java/com/willyoubackend/domain/user_profile/entity/UserRecommendations.java, src/main/java/com/willyoubackend/domain/user_profile/service/UserProfileService.java
레디스 사용일시 중단: 굳이 사용할 이유가 없어서
Resolves: #131
Ref: None
=> [#131] Feat: "User Profile Recommendations Fixed"

src/main/java/com/willyoubackend/domain/dating/repository/ActivitiesDatingRepository.java, src/main/java/com/willyoubackend/domain/dating/service/ActivityService.java, src/main/java/com/willyoubackend/domain/dating/service/DatingService.java
Modifying delete for Activity and Dating
Resolves: #136
Ref: None
=> [#136] Fix: "ActivitiesDating Fixed"

src/main/java/com/willyoubackend/domain/websocket/entity/ChatRoomDto.java, src/main/java/com/willyoubackend/domain/websocket/entity/SocketMessage.java, src/main/java/com/willyoubackend/domain/websocket/service/ChatRoomService.java
채팅룸 목록 조회 데이터 종류 (age, location, info, mbti etc)추가
Resolves: #132
Ref: None
=> [#132] Add: "chatroom info"

src/main/java/com/willyoubackend/domain/websocket/service/ChatRoomService.java
최근 메시지 순으로 채팅방 목록 조회
Resolves: #132
Ref: None
=> [#132] Fix: "chatroom list sequence"

src/main/java/com/willyoubackend/domain/websocket/entity/SocketMessage.java
필드에 기본값 false 추가
Resolves: #132
Ref: None
Related to: #132
=> [#132] Fix: "chatMessage is_read"

src/main/java/com/willyoubackend/domain/user/security/JwtAuthenticationFilter.java, src/main/java/com/willyoubackend/domain/user/security/JwtAuthorizationFilter.java, src/main/java/com/willyoubackend/domain/websocket/entity/SocketMessage.java
499 Raise in the case of expired access token
Resolves: #138
Ref: None
=> [#138] Fix: "JWT custom error code return"

src/main/java/com/willyoubackend/domain/user/repository/UserRepositoryImpl.java, src/main/java/com/willyoubackend/domain/user_profile/repository/ProfileImageRepositoryImpl.java, src/main/java/com/willyoubackend/domain/user_profile/repository/UserProfileRepositoryImpl.java
QueryDSL NPE 대응
Resolves: #147
Ref: None
=> [#147]Feat: "QueryDSL NPE"

src/main/java/com/willyoubackend/domain/user_like_match/service/UserLikeService.java, src/main/java/com/willyoubackend/domain/user_like_match/service/UserMatchStatusService.java, src/main/java/com/willyoubackend/global/exception/ErrorCode.java
에러코드 분류
Resolves: #151
Ref: None
=> [#151]Fix: "ErrorCode Sorting"

src/main/java/com/willyoubackend/global/exception/ErrorCode.java
에러코드 스테이터스 변경
Resolves: #153
Ref: None
=> [#153]Fix: "Error Code Status"

src/main/java/com/willyoubackend/domain/user_like_match/service/UserLikeStatusService.java
Resolves: #160
Ref: None
Related to: #158
=> [#160] Fix: "LikeStatusResponseDto Fixed"

src/main/java/com/willyoubackend/domain/user_profile/dto/UserOwnProfileResponseDto.java
유저 프로필 enum 값 한글로 변환(location, religion)
Resolves: #171
Ref: None
=> [#171]Fix: "Enum Korean"

src/main/java/com/willyoubackend/domain/user_profile/entity/LocationEnum.java, src/main/java/com/willyoubackend/domain/user_profile/entity/ReligionEnum.java, src/main/java/com/willyoubackend/domain/user_profile/entity/UserProfileEntity.java
유저 프로필 enum Request 한글로 변환(location, religion)
Resolves: #173
Ref: None
=> [#173]Fix: "Enum Korean Request"

src/main/java/com/willyoubackend/domain/dating/dto/DatingResponseDto.java
=> [#178] Fix: "Dating ResponseDto Fixed"

src/main/java/com/willyoubackend/domain/user_profile/entity/ReligionEnum.java
종교 '없음' 추가
Resolves: #180
Ref: None
=> [#180]Fix: "ReligionEnum-Fix"

src/main/java/com/willyoubackend/domain/user/controller/UserController.java, src/main/java/com/willyoubackend/domain/user/service/UserService.java, src/main/java/com/willyoubackend/domain/user_profile/controller/UserProfileController.java, src/main/java/com/willyoubackend/domain/user_profile/entity/UserProfileEntity.java, src/main/java/com/willyoubackend/domain/user_profile/service/UserProfileService.java
API 요청시 userId 필요 없음
Resolves: #182
Ref: None
Related to: #182
=> [#182] Fix: "isNew API"

src/main/java/com/willyoubackend/global/util/S3Uploader.java
Heic format image will be converted to jpeg or jpg
Resolves: #188
Ref: None
=> [#188] Add: "Heic format upload config"

src/main/java/com/willyoubackend/domain/user/repository/UserRepositoryCustom.java, src/main/java/com/willyoubackend/domain/user/repository/UserRepositoryImpl.java, src/main/java/com/willyoubackend/domain/user_profile/dto/UserOwnProfileResponseDto.java, src/main/java/com/willyoubackend/domain/user_profile/dto/UserProfileResponseDto.java, src/main/java/com/willyoubackend/domain/user_profile/entity/LocationEnum.java, src/main/java/com/willyoubackend/domain/user_profile/entity/MbtiEnum.java, src/main/java/com/willyoubackend/domain/user_profile/entity/ReligionEnum.java, src/main/java/com/willyoubackend/domain/user_profile/entity/UserProfileEntity.java, src/main/java/com/willyoubackend/domain/user_profile/service/UserProfileService.java
Enum -> Varchar (religion, mbti, location)
Resolves: #190
Ref: None
=> [#190]Fix: "Delete Enum"

src/main/java/com/willyoubackend/domain/report/service/ReportSerivce.java
Collectors 추가
Resolves: #176
Ref: #176
Related to: #176
=> [#176] Fix: "Report"

src/main/java/com/willyoubackend/domain/user_profile/controller/UserProfileController.java, src/main/java/com/willyoubackend/domain/user_profile/service/UserProfileService.java
ADMIN 권한 추가
Resolves: #182
Ref: None
Related to: #182
=> [#182] Fix: "ADMIN Deactivate Status API"

src/main/java/com/willyoubackend/domain/dating/controller/DatingController.java, src/main/java/com/willyoubackend/domain/dating/dto/DatingResponseDto.java, src/main/java/com/willyoubackend/domain/dating/entity/Dating.java, src/main/java/com/willyoubackend/domain/dating/repository/qdsl/DatingCustomRepository.java, src/main/java/com/willyoubackend/domain/dating/repository/qdsl/DatingCustomRepositoryImpl.java, src/main/java/com/willyoubackend/domain/dating/service/DatingService.java, src/main/java/com/willyoubackend/domain/user_like_match/repository/UserMatchStatusRepository.java, src/main/java/com/willyoubackend/domain/user_like_match/repository/qdsl/UserMatchStatusCustomRepository.java, src/main/java/com/willyoubackend/domain/user_like_match/repository/qdsl/UserMatchStatusCustomRepositoryImpl.java
Dating ResponseDto and List Modified (filtered)
Resolves: #181
Ref: None
=> [#181] Add: "Dating Response and List modified"

src/main/java/com/willyoubackend/domain/dating/dto/DatingResponseDto.java, src/main/java/com/willyoubackend/domain/dating/repository/qdsl/DatingCustomRepositoryImpl.java, src/main/java/com/willyoubackend/domain/dating/service/DatingService.java, src/main/java/com/willyoubackend/domain/user_like_match/controller/UserLikeNopeStatusController.java, src/main/java/com/willyoubackend/domain/user_like_match/repository/qdsl/UserLikeStatusCustomRepositoryImpl.java, src/main/java/com/willyoubackend/domain/user_like_match/repository/qdsl/UserMatchStatusCustomRepository.java, src/main/java/com/willyoubackend/domain/user_like_match/repository/qdsl/UserMatchStatusCustomRepositoryImpl.java, src/main/java/com/willyoubackend/domain/user_like_match/repository/qdsl/UserNopeStatusCustomRepositoryImpl.java, src/main/java/com/willyoubackend/domain/user_like_match/service/UserLikeService.java, src/main/java/com/willyoubackend/domain/user_like_match/service/UserLikeStatusService.java
User, Like Status and Match fixed
=> [#195 ]Add/#195 user match like

src/main/java/com/willyoubackend/domain/sse/controller/AlertController.java, src/main/java/com/willyoubackend/domain/user_like_match/service/UserLikeService.java
SSE 매치 알림 추가
Resolves: #200
Ref: None
=> [#200]Fix: "SSE add match"

src/main/java/com/willyoubackend/domain/user/entity/UserEntity.java, src/main/java/com/willyoubackend/global/entity/Timestamped.java
=> [#202] Fix: "Time and Fetchtype fix"

src/main/java/com/willyoubackend/domain/user/repository/UserRepositoryImpl.java
=> [#205] Fix: "Location Removed"

src/main/java/com/willyoubackend/domain/dating/dto/DatingDetailResponseDto.java, src/main/java/com/willyoubackend/domain/user_like_match/repository/UserMatchStatusRepository.java, src/main/java/com/willyoubackend/domain/user_profile/controller/UserProfileController.java, src/main/java/com/willyoubackend/domain/user_profile/dto/UserProfileMatchResponseDto.java, src/main/java/com/willyoubackend/domain/user_profile/service/UserProfileService.java, src/main/resources/application.properties
=> [#208] Add:"Time zone added with matchId Return"

src/main/java/com/willyoubackend/domain/user_like_match/entity/UserMatchStatus.java, src/main/java/com/willyoubackend/domain/user_like_match/service/UserMatchStatusService.java
=> [#210] Fix:"UserMatch Soft delete"

build.gradle
=> [#212] Feat:"Sentry Config"

src/main/java/com/willyoubackend/domain/user/entity/UserEntity.java, src/main/java/com/willyoubackend/domain/user_profile/service/ProfileImageService.java, src/main/java/com/willyoubackend/global/util/S3Uploader.java
=> [#215] Fix:"image fixed"

src/main/java/com/willyoubackend/domain/sse/controller/AlertController.java
SSE nginx 설정
Resolves: #220
Ref: None
=> [#220]Fix: "SSE nginx"

src/main/java/com/willyoubackend/domain/sse/service/AlertService.java
SSE ReadStatus
Resolves: #222
Ref: None
=> [#222]Fix: "SSE ReadStatus"

build.gradle, src/main/java/com/willyoubackend/domain/sse/dto/AlertResponseDto.java, src/main/java/com/willyoubackend/domain/sse/entity/Alert.java, src/main/java/com/willyoubackend/domain/sse/service/AlertService.java
SSE time
Resolves: #229
Ref: None
=> [#229]Fix: "SSE time"

src/main/java/com/willyoubackend/domain/user/service/KakaoService.java
도메인 변경으로 카카오 redirect uri 수정
Resolves: none
Ref: none
Related to: #4, #60
=> [#231] Fix: "Fix kakao redirect uri"

src/main/java/com/willyoubackend/domain/sse/service/AlertService.java
SSE LOG CHECK
Resolves: None
Ref: None
Related to: #214
=> [#234] Fix: "Log Check"

src/main/java/com/willyoubackend/domain/user_like_match/service/UserLikeStatusService.java, src/main/java/com/willyoubackend/global/util/S3Uploader.java
S3 and Like Status
Resolves: None
Ref: None
Related to: #228
=> [#228] Fix: "Minor Fix"

src/main/java/com/willyoubackend/domain/sse/dto/AlertResponseDto.java, src/main/java/com/willyoubackend/domain/sse/dto/UserDto.java
SSE Image
Resolves: #236
Ref: None
=> [#236]Fix: "SSE Image"

src/main/java/com/willyoubackend/domain/user_profile/entity/UserRecommendation.java, src/main/java/com/willyoubackend/domain/user_profile/service/UserProfileService.java
Default Recommendation Added
Resolves: None
Ref: None
Related to: #238
=> [#238] Add: "Default Recommendation Added"

src/main/java/com/willyoubackend/domain/dating/controller/DatingController.java, src/main/java/com/willyoubackend/domain/dating/dto/DatingDetailResponseDto.java, src/main/java/com/willyoubackend/domain/dating/dto/DatingImageRequestDto.java, src/main/java/com/willyoubackend/domain/dating/service/DatingService.java
Default Image created for No Pic
Resolves: #246
Ref: None
Related to: #228
=> [#246] Fix: "Dating Image Fix"

src/main/java/com/willyoubackend/domain/user_like_match/service/UserLikeService.java
Log set
Resolves: #248
Ref: None
Related to: #248
=> [#248] Fix: "User Like Fix"

src/main/java/com/willyoubackend/domain/websocket/controller/StompController.java
Log set
Resolves: #251
Ref: None
Related to: #251
=> [#251] Fix: "Logs for StompController"

src/main/java/com/willyoubackend/domain/sse/service/AlertService.java
Log set
Resolves: #251
Ref: None
Related to: #251
=> [#251] Fix: "Logs for SSE"

src/main/java/com/willyoubackend/domain/dating/service/DatingService.java
Image modified updated
Resolves: #256
Ref: None
=> [#256] Fix: "Image Modify fixed"

src/main/java/com/willyoubackend/domain/dating/controller/DatingController.java, src/main/java/com/willyoubackend/domain/dating/service/DatingService.java
Dating Delete
Resolves: #258
Ref: None
=> [#258] Add: "Dating delete added"

src/main/java/com/willyoubackend/domain/sse/service/AlertService.java
Null Check
Resolves: #258
Ref: None
=> [#248] Fix: "User Like SSE fix trial 1"

src/main/java/com/willyoubackend/domain/sse/service/AlertService.java
Null Check -> sseEmitter and emitter
Resolves: #248
Ref: None
=> [#248] Fix: "User Like SSE fix trial 2"

src/main/java/com/willyoubackend/domain/sse/service/AlertService.java
Rollback sseEmitters
Resolves: #248
Ref: None
=> [#248] Fix: "User Like SSE fix trial 4"

src/main/java/com/willyoubackend/domain/user_profile/controller/UserProfileController.java, src/main/java/com/willyoubackend/domain/user_profile/dto/UserMainResponseDto.java, src/main/java/com/willyoubackend/domain/user_profile/service/UserProfileService.java
=> [#264] Add: "User Match Status & User Recommendations"
